"""tooth_edit

Revision ID: 43aa748a99af
Revises: 706ac7c5a83d
Create Date: 2023-07-05 16:44:40.791960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43aa748a99af'
down_revision = '706ac7c5a83d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tooth', 'numeration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'tooth', ['numeration'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tooth', type_='unique')
    op.alter_column('tooth', 'numeration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
