"""odontogram

Revision ID: 706ac7c5a83d
Revises: a85081b133d0
Create Date: 2023-06-26 09:15:12.967833

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '706ac7c5a83d'
down_revision = 'a85081b133d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment',
                    sa.Column('treatment_id', sa.Integer(), nullable=False),
                    sa.Column('name_treatment', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('treatment_id')
                    )
    op.create_index(op.f('ix_treatment_treatment_id'), 'treatment', ['treatment_id'], unique=False)
    op.create_table('type_odontogram',
                    sa.Column('type_odontogram_id', sa.Integer(), nullable=False),
                    sa.Column('name_type', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('type_odontogram_id')
                    )
    op.create_index(op.f('ix_type_odontogram_type_odontogram_id'), 'type_odontogram', ['type_odontogram_id'],
                    unique=False)
    op.create_table('odontogram',
                    sa.Column('odontogram_id', sa.Integer(), nullable=False),
                    sa.Column('patient_id', sa.Integer(), nullable=False),
                    sa.Column('type_odontogram_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
                    sa.ForeignKeyConstraint(['type_odontogram_id'], ['type_odontogram.type_odontogram_id'], ),
                    sa.PrimaryKeyConstraint('odontogram_id')
                    )
    op.create_index(op.f('ix_odontogram_odontogram_id'), 'odontogram', ['odontogram_id'], unique=False)
    op.create_table('detail_odontogram',
                    sa.Column('detail_odontogram_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('odontogram_id', sa.Integer(), nullable=False),
                    sa.Column('tooth_id', sa.Integer(), nullable=False),
                    sa.Column('treatment_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['odontogram_id'], ['odontogram.odontogram_id'], ),
                    sa.ForeignKeyConstraint(['tooth_id'], ['tooth.tooth_id'], ),
                    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.treatment_id'], ),
                    sa.PrimaryKeyConstraint('detail_odontogram_id', 'odontogram_id')
                    )
    op.create_index(op.f('ix_detail_odontogram_detail_odontogram_id'), 'detail_odontogram', ['detail_odontogram_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detail_odontogram_detail_odontogram_id'), table_name='detail_odontogram')
    op.drop_table('detail_odontogram')
    op.drop_index(op.f('ix_odontogram_odontogram_id'), table_name='odontogram')
    op.drop_table('odontogram')
    op.drop_index(op.f('ix_type_odontogram_type_odontogram_id'), table_name='type_odontogram')
    op.drop_table('type_odontogram')
    op.drop_index(op.f('ix_treatment_treatment_id'), table_name='treatment')
    op.drop_table('treatment')
    # ### end Alembic commands ###
