"""init

Revision ID: a85081b133d0
Revises: 
Create Date: 2023-06-04 14:47:37.679278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85081b133d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_category',
    sa.Column('image_category_id', sa.Integer(), nullable=False),
    sa.Column('image_category_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('image_category_id')
    )
    op.create_index(op.f('ix_image_category_image_category_id'), 'image_category', ['image_category_id'], unique=False)
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patient_email'), 'patient', ['email'], unique=True)
    op.create_index(op.f('ix_patient_patient_id'), 'patient', ['patient_id'], unique=False)
    op.create_table('tooth',
    sa.Column('tooth_id', sa.Integer(), nullable=False),
    sa.Column('tooth_name', sa.String(length=50), nullable=True),
    sa.Column('numeration', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tooth_id')
    )
    op.create_index(op.f('ix_tooth_tooth_id'), 'tooth', ['tooth_id'], unique=False)
    op.create_table('dental_image',
    sa.Column('dental_image_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_category_id'], ['image_category.image_category_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('dental_image_id')
    )
    op.create_index(op.f('ix_dental_image_dental_image_id'), 'dental_image', ['dental_image_id'], unique=False)
    op.create_table('image_tooth',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tooth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['dental_image.dental_image_id'], ),
    sa.ForeignKeyConstraint(['tooth_id'], ['tooth.tooth_id'], ),
    sa.PrimaryKeyConstraint('image_id', 'tooth_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_tooth')
    op.drop_index(op.f('ix_dental_image_dental_image_id'), table_name='dental_image')
    op.drop_table('dental_image')
    op.drop_index(op.f('ix_tooth_tooth_id'), table_name='tooth')
    op.drop_table('tooth')
    op.drop_index(op.f('ix_patient_patient_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_image_category_image_category_id'), table_name='image_category')
    op.drop_table('image_category')
    # ### end Alembic commands ###
